spring:
    profiles:
        active:
         - dev
---
spring:
    profiles: dev
service1
    port: 10001
service2
    port: 10002
service3
    port: 10003
---
spring:
    profiles: test
service1
    port: 11001
service2
    port: 11002
service3
    port: 11003
        
