spring:
    profiles:
        active:
         - dev
---
spring:
    profiles: dev
service:
  service1Port: 10001
  service2Port: 10002
  service3Port: 10003
---
spring:
    profiles: test
service:
  service1Port: 11001
  service2Port: 11002
  service3Port: 11003
        
