spring:
    profiles:
        active:
         - dev
---
spring:
    profiles: service1
server:
    port: 8101
---
spring:
    profiles: service2
server:
    port: 8102
---
spring:
    profiles: service3
server:
    port: 8103
        
