spring:
    profiles:
        active:
        - dev
---
server:
    port: 8001
spring:
    profiles: dev
    application:
        name: microservicecloud-config-dept-client
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql:///cloudDb01?characterEncoding=utf8&useSSL=false&serverTimeZone=UTC&zeroDateTimeBehavior=CONVERT_TO_NULL
        username: root
        password: root
        dbcp2:
            min-idle: 5
            initial-size: 5
            max-total: 5
            max-wait-mills: 200
       mybatis:
        config-locations: classpath:mybatis/mybatis.cfg.xml
        type-aliases-packages: com.itshunn.springcloud.entities
        mapper-locations:
        - classpath:mybatis/mapper/**/*.xml
       eureka:
        client:
            server-url:
                defaultZone: http//eureka7001.com:7001/eureka
info:
    app.name: itshunn-microservicecloud-springcloudconfig-01
    company.name: www.itshunn.com
    build.artfaactId: $project.artifactId$
    build.version: $project.version$
---
server:
    port: 8001
spring:
    profiles: test
    application:
        name: microservicecloud-config-dept-client
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql:///cloudDb02?characterEncoding=utf8&useSSL=false&serverTimeZone=UTC&zeroDateTimeBehavior=CONVERT_TO_NULL
        username: root
        password: root
        dbcp2:
            min-idle: 5
            initial-size: 5
            max-total: 5
            max-wait-mills: 200
       mybatis:
        config-locations: classpath:mybatis/mybatis.cfg.xml
        type-aliases-packages: com.itshunn.springcloud.entities
        mapper-locations:
        - classpath:mybatis/mapper/**/*.xml
       eureka:
        client:
            server-url:
                defaultZone: http//eureka7001.com:7001/eureka
info:
    app.name: itshunn-microservicecloud-springcloudconfig-01
    company.name: www.itshunn.com
    build.artfaactId: $project.artifactId$
    build.version: $project.version$
                